
project(testlib4zip LANGUAGES CXX)

add_executable(testturbosqueeze test.cpp)
# target_compile_options(testturbosqueeze PRIVATE "-fsanitize=address")
# target_link_options(testturbosqueeze PRIVATE "-fsanitize=address")
target_link_libraries(testturbosqueeze PRIVATE turbosqueeze)

add_test(NAME test_tsq_context COMMAND testturbosqueeze test_tsq_context)
add_test(NAME test_tsq_compress COMMAND testturbosqueeze test_tsq_compress)
add_test(NAME test_tsq_compress_optimal COMMAND testturbosqueeze test_tsq_compress_optimal)
add_test(NAME test_tsq_context_mt COMMAND testturbosqueeze test_tsq_context_mt)
add_test(NAME test_tsq_compress_mt COMMAND testturbosqueeze test_tsq_compress_mt)
add_test(NAME test_tsq_queue_mt COMMAND testturbosqueeze test_tsq_queue_mt)
add_test(NAME test_tsq_context_mt2 COMMAND testturbosqueeze test_tsq_context_mt2)
add_test(NAME test_tsq_decompress_mt COMMAND testturbosqueeze test_tsq_decompress_mt)
add_test(NAME test_tsq_compress_async_mt COMMAND testturbosqueeze test_tsq_compress_async_mt)
add_test(NAME test_tsq_decompress_async_mt COMMAND testturbosqueeze test_tsq_decompress_async_mt)
add_test(NAME test_tsq_massive_async_mt COMMAND testturbosqueeze test_tsq_massive_async_mt)
add_test(NAME test_tsq_huffmann COMMAND testturbosqueeze test_tsq_huffmann)
add_test(NAME test_tsq_compress_1 COMMAND testturbosqueeze test_tsq_compress_1)
add_test(NAME test_tsq_compress_2 COMMAND testturbosqueeze test_tsq_compress_2)
add_test(NAME test_tsq_compress_3 COMMAND testturbosqueeze test_tsq_compress_3)
add_test(NAME test_tsq_compress_4 COMMAND testturbosqueeze test_tsq_compress_4)
add_test(NAME test_tsq_compress_5 COMMAND testturbosqueeze test_tsq_compress_5)
add_test(NAME test_tsq_compress_6 COMMAND testturbosqueeze test_tsq_compress_6)
add_test(NAME test_tsq_compress_7 COMMAND testturbosqueeze test_tsq_compress_7)
add_test(NAME test_tsq_compress_file COMMAND testturbosqueeze test_tsq_compress_file)
